package org.usfirst.frc.team3925.robot;

public final class RobotMap {
	// cannot create instances of this class
	private RobotMap() {}
	
	public static final int 
			DRIVE_LEFT_MOTOR = 0,
			DRIVE_RIGHT_MOTOR = 1,
			DRIVE_LEFT_ENCODER_A = 2,
			DRIVE_LEFT_ENCODER_B = 3,
			DRIVE_RIGHT_ENCODER_A = 0,
			DRIVE_RIGHT_ENCODER_B = 1,
			
			ELEVATOR_LEFT_TALON = 2,
			ELEVATOR_RIGHT_TALON = 3,
			ELEVATOR_ENCODER_A = 4,
			ELEVATOR_ENCODER_B = 5,
			ELEVATOR_SWITCH_1 = 9,
			ELEVATOR_SWITCH_2 = 8,
			
			INTAKE_VICTOR_LEFT_BACK = 4,
			INTAKE_VICTOR_RIGHT_BACK = 5,
			INTAKE_VICTOR_LEFT_FRONT = 6,
			INTAKE_VICTOR_RIGHT_FRONT = 7,
			INTAKE_ROLLER = 9,
			INTAKE_RIGHT_DOUBLE_SOLENOID_A = 0,
			INTAKE_RIGHT_DOUBLE_SOLENOID_B = 1,
			INTAKE_LEFT_DOUBLE_SOLENOID_A = 2,
			INTAKE_LEFT_DOUBLE_SOLENOID_B = 3,
			
			COMPRESSOR = 0,
			
			JOYSTICK_XBOX_DRIVER = 0,
			JOYSTICK_XBOX_SHOOTER = 1;
	
}
